#!/bin/bash 
DEB_MIRROR="http://deb.debian.org/debian/"
DEB_SECURITY_MIRROR="http://security.debian.org/debian-security/"
lb config noauto --clean \
	--mode debian \
	--distribution trixie \
	--debian-installer netinst \
	--debian-installer-distribution trixie \
	--debian-installer-gui false \
	--bootloaders grub-efi \
	--bootappend-live "boot=live toram=filesystem.squashfs components locales=en_US.UTF-8 hostname=livebuild username=tuhadmin user-fullname=tuhadmin timezone=America/New_York persistence persistence-encryption=luks persistence-media=removable-usb" \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--binary-filesystem ext4 \
	--checksums sha256 \
	--source false \
	--system normal \
	--firmware-binary true \
	--firmware-chroot false \
	--parent-mirror-bootstrap "${DEB_MIRROR}" \
	--apt-recommends false \
	--backports true \
	--security false \
	--archive-areas "main contrib non-free non-free-firmware" \
	--apt-options "--yes \
--option=Dpkg::Options::=--force-confdef \
--option=Dpkg::Options::=--force-confold \
--option=Dpkg::Options::=--force-unsafe-io" \
	--linux-packages "linux-image linux-headers" \
	 "${@}"
