name: Release

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "debian:trixie"
      options: --privileged

    steps:
      - name: Cache live-build files
        uses: actions/cache@v6
        with:
          path: cache
          key: ${{ runner.os }}-build

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install --yes \
            debian-archive-keyring \
            ca-certificates \
            xorriso \
            squashfs-tools \
            isolinux \
            syslinux-common \
            debootstrap \
            live-build

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        run: |
          lb config
          lb build

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.RUNNER_TOKEN }}
          files: |
            live-image-amd64.hybrid.iso
